# Generated by Django 4.1.7 on 2023-04-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_image_onlineuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL'),
        ),
    ]
