# Generated by Django 4.1.7 on 2023-04-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL'),
        ),
    ]
